name: CraftSlotCommands4
main: com.gmail.bobason01.CraftSlotCommands
version: 5.0
api-version: 1.13
author: crston
depend: [ProtocolLib]
commands:
  craftslotcommands:
    description: Admin command for CraftSlotCommands.
    aliases: [csc]
  crston:
    description: Are you having trouble?
    usage: /crston
    permission: false
permissions:
  csc.admin:
    description: Access to the CraftSlotCommands command.
    default: op
